version: 2.1

jobs:
  cb:
    docker:
      - image: circleci/python:latest
    working_directory: /tmp
    steps: 
      - run: echo "Hi Chris"
      - run: echo $CIRCLE_BUILD_NUM
      - run: mkdir -p workspace 
      - run: echo "This is from the first job." > workspace/test
      - persist_to_workspace:
          root: workspace
          paths:
            - test

  bb:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cat test
      - run: echo "Hi Benish"
      - run: echo $CIRCLE_BUILD_NUM
  


workflows:
  version: 2.1
  cb_and_bb:
    jobs:
      - cb
      - bb:
          requires:
            - cb



